### ISSUE TITLE
SA - Labels for Geography Not Displaying on Custom Report

### ISSUE THREAD

**Issue by tgilcrest** [WorldBank-Transport/DRIVER#553] opened 2016-05-25 03:15 UTC
When using a Geography layer for either rows or columns in the custom report, the labels aren't being displayed.  This happens for both Provinces and Maintenance Contracts, so doesn't seem to be an Arabic issue.  Labels _do_ work when using the Geographic Aggregation option, when non-geographic rows / columns are selected.

![image](https://cloud.githubusercontent.com/assets/14098314/15527079/ec743660-223f-11e6-9a2d-9bb9fa0b3542.png)

**Comment by ddohler** [comment] 2016-05-25 13:34
This is a duplicate of #536 but that ended up being two issues in one, so I'll leave this open until @kshepard confirms that both aspects of it were resolved.

**Comment by kshepard** [comment] 2016-05-25 13:42
I only fixed the problem with enumerated fields displaying correctly -- didn't realize geographies were also not displaying. It's a separate path of logic for geographies, but will be an easy fix.

**Closed** 2016-05-25 17:38 UTC
