### ISSUE TITLE
Nothing appears in dashboard and in map

### ISSUE THREAD

**Issue by AntoninoFRED** [WorldBank-Transport/DRIVER#792] opened 2019-06-05 10:30 UTC
We have finally been able to store crash data in the web application, to test it.
While the data are correctly visibile in the record list, nothing appears in dashboard and in map.
Can you please explain how to solve?

**Comment by rmartz** [comment] 2019-06-26 17:43
That's interesting that records would load in the Record List, but not on the Map page. Do you see the error from #793 on the Dashboard or Map pages when you're experiencing this? If that issue seems to be unrelated, can you open your browser's Developer Tools feature and refresh - do you see any failed requests? In Google Chrome, they would appear in the "Network" tab with "XHR" selected, and would be shown in red text.

**Comment by tgilcrest** [comment] 2019-07-11 18:58
It looks like this was resolved in #793. If you see this again and have reproduction steps then we can investigate.

**Closed by tgilcrest** 2019-07-11 18:58 UTC
